name: Deploy MechBot-2X
on:
  push:
    branches: [main]
    paths: 
      - 'projects/mechbot-2x/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: rustlang/rust:nightly

    steps:
      - uses: actions/checkout@v4
      
      - name: Build Rust Code
        run: |
          cd projects/mechbot-2x
          cargo build --release
          strip target/release/mechbot

      - name: Deploy to ROS2
        env:
          ROS_DISTRO: humble
        run: |
          scp target/release/mechbot user@robot:/opt/ros/$ROS_DISTRO/bin/
