[workspace]
members = [
    "mechbot-2x",
    "atomic-rs", 
    "oxide-security"
]
resolver = "2"
// ¡Verificación en Rust!
#[test]
fn test_codeql_setup() {
    assert!(std::path::exists(".github/codeql"));
    println!("✅ Todo listo para escanear");
}
