[package]
name = "mechcore"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }

[[bin]]
name = "mechai"
path = "src/main.rs"
