[package]
name = "mechcore"
version = "0.2.0"
edition = "2021"

[features]
ros2 = ["r2r"]

[dependencies]
r2r = { version = "0.8", optional = true }
serde = { version = "1.0", features = ["derive"] }

[[bin]]
name = "mechai"
path = "src/main.rs"
