name: MechMind Hyperdrive

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      turbo_mode:
        description: "Activar modo turbo"
        required: false
        default: "false"

  jobs:
permissions:
       contents: read
       pull-requests: write
       build:
       runs-on: ubuntu-latest
       steps:
        - uses: actions/checkout@v4
        - uses: actions-rs/toolchain@v1
            with:
            toolchain: stable
          override: true
      - name: Build MechCore
        working-directory: projects/mechcore
        run: cargo build --release
      - name: ROS2 Setup
        if: ${{ github.event.inputs.turbo_mode == 'true' }}
        run: |
          echo "🦄 ROS2 simulation activated"
          mkdir -p projects/ros2/src
