name: MechCore CI

on: [push, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '-C target-feature=-crt-static'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Verify structure
        run: |
          mkdir -p projects/mechcore/src
          [ -f projects/mechcore/src/main.rs ] || {
            echo 'fn main() {}' > projects/mechcore/src/main.rs
          }
          
      - name: Build Release
        working-directory: projects/mechcore
        run: |
          cargo build --release
          ./target/release/mechai
